"""empty message

Revision ID: 5640cad1c17e
Revises: f08e6e5c7287
Create Date: 2020-07-07 13:49:03.252336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5640cad1c17e'
down_revision = 'f08e6e5c7287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('user_username', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call')
    # ### end Alembic commands ###
