"""empty message

Revision ID: d2ce66a927e2
Revises: 5640cad1c17e
Create Date: 2020-07-07 15:15:59.697493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ce66a927e2'
down_revision = '5640cad1c17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zvonok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('user_username', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('call')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=True),
    sa.Column('user_username', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('zvonok')
    # ### end Alembic commands ###
