"""improving

Revision ID: f08e6e5c7287
Revises: a0e8a29439f2
Create Date: 2020-06-25 14:13:56.777066

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f08e6e5c7287'
down_revision = 'a0e8a29439f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('article', sa.String(length=100), nullable=True),
                    sa.Column('publish_date', sa.DateTime(), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('user', sa.Column('avatar', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'avatar')
    op.drop_table('new')
    # ### end Alembic commands ###
